const BUILT_INS = [
  {id:'basics',title:'Daily basics',description:'The words you use every day.',color:'peach',words:[['hello','xin chào'],['thank you','cảm ơn'],['yes','có'],['no','không'],['please','làm ơn'],['goodbye','tạm biệt'],['sorry','xin lỗi'],['friend','bạn'],['water','nước'],['delicious','ngon']]},
  {id:'food',title:'Vietnamese food',description:'Order with confidence.',color:'mint',words:[['rice','cơm'],['noodles','mì'],['coffee','cà phê'],['chicken','gà'],['fish','cá'],['vegetables','rau'],['spicy','cay'],['delicious','ngon']]},
  {id:'travel',title:'Getting around',description:'Find your way around Vietnam.',color:'lavender',words:[['where','ở đâu'],['left','trái'],['right','phải'],['straight','thẳng'],['street','đường'],['airport','sân bay'],['hotel','khách sạn'],['near','gần']]}];
const $=s=>document.querySelector(s), views={library:$('#library'),quiz:$('#quiz'),complete:$('#complete')};
let custom=JSON.parse(localStorage.getItem('vietwords-quizzes')||'[]'), active=null, queue=[], index=0, attempts=0, correct=0, answered=false;
const esc=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem('vietwords-quizzes',JSON.stringify(custom));}
function card(lesson, own=false){return `<article class="lesson-card ${lesson.color||'blue'}"><div class="lesson-art">${own?'✎':'✦'}</div><div class="lesson-info"><h3>${esc(lesson.title)}</h3><p>${esc(lesson.description||`${lesson.words.length} words to practice.`)}</p><small>${lesson.words.length} words</small></div>${own?`<button class="delete" data-delete="${lesson.id}" aria-label="Delete ${esc(lesson.title)}">×</button>`:''}<button class="card-arrow" data-start="${lesson.id}" aria-label="Start ${esc(lesson.title)}">→</button></article>`}
function renderLibrary(){ $('#custom-section').hidden=!custom.length; $('#custom-count').textContent=custom.length; $('#custom-lessons').innerHTML=custom.map(x=>card(x,true)).join(''); $('#public-lessons').innerHTML=BUILT_INS.map(card).join(''); document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start([...custom,...BUILT_INS].find(x=>x.id===b.dataset.start))); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{custom=custom.filter(x=>x.id!==b.dataset.delete);save();renderLibrary()});}
function show(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('active',k===name)); window.scrollTo({top:0,behavior:'smooth'});}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function start(lesson){active=lesson; queue=shuffle(lesson.words).map(([en,vi])=>({en,vi,tries:0})); index=0;attempts=0;correct=0;show('quiz');renderQuestion();}
function renderQuestion(){const item=queue[index];answered=false;$('#quiz-category').textContent=active.title.toUpperCase();$('#quiz-title').textContent=item.en;$('#quiz-subtitle').textContent='';$('#progress-label').textContent=`${index+1} / ${queue.length}`;$('#progress-bar').style.width=`${index/queue.length*100}%`;$('#feedback').className='feedback';$('#feedback').textContent='';$('#next-button').hidden=true;const distractors=shuffle(queue.filter((_,i)=>i!==index).map(x=>x.vi)).slice(0,3);$('#answers').innerHTML=shuffle([item.vi,...distractors]).map((a,i)=>`<button class="answer" data-answer="${esc(a)}"><span>${String.fromCharCode(65+i)}</span>${esc(a)}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(b));}
function answer(button){if(answered)return;answered=true;attempts++;const item=queue[index], right=button.dataset.answer===item.vi; if(right)correct++;button.classList.add(right?'correct':'wrong');document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;if(b.dataset.answer===item.vi)b.classList.add('correct')});if(!right){item.tries++;queue.push(item);$('#feedback').textContent=`Not quite — the answer is “${item.vi}”. We’ll see this one again.`;$('#feedback').classList.add('bad')}else{$('#feedback').textContent=item.tries?'Nice recovery.':'Correct — well remembered.';$('#feedback').classList.add('good')}$('#progress-bar').style.width=`${(index+1)/queue.length*100}%`;$('#next-button').hidden=false;}
function next(){index++; if(index>=queue.length)finish();else renderQuestion()}
function finish(){const pct=Math.round(correct/attempts*100)||0;$('#score-value').textContent=`${pct}%`;$('#complete-copy').textContent=`You got ${correct} right out of ${attempts} attempts.`;show('complete');$('#streak').textContent=Number(localStorage.getItem('vietwords-streak')||0)+1;localStorage.setItem('vietwords-streak',$('#streak').textContent)}
$('#creator-form').onsubmit=e=>{e.preventDefault();const title=$('#quiz-name').value.trim(), lines=$('#quiz-data').value.trim().split(/\n+/).filter(Boolean), words=[];for(const line of lines){const parts=line.split(/\s+-\s+/);if(parts.length!==2||!parts[0].trim()||!parts[1].trim()){ $('#creator-error').textContent=`Couldn’t read “${line}”. Use English - Vietnamese.`;return}words.push([parts[0].trim(),parts[1].trim()])}if(words.length<4){$('#creator-error').textContent='Add at least 4 word pairs to make a quiz.';return}custom.unshift({id:`custom-${Date.now()}`,title,description:'Created by you.',color:'blue',words});save();e.target.reset();$('#creator-error').textContent='';renderLibrary();document.querySelector('#custom-section').scrollIntoView({behavior:'smooth'})};
$('#next-button').onclick=next;$('#retry-button').onclick=()=>start(active);$('#library-button').onclick=()=>{renderLibrary();show('library')};$('#back-button').onclick=()=>{renderLibrary();show('library')};$('#pause-button').onclick=()=>alert('Take a breath. Your progress is safe on this screen.');$('#streak').textContent=localStorage.getItem('vietwords-streak')||0;renderLibrary();
